cakephp/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'FichasAlquiler', 'action' => 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

cakephp/src/Model/Table/CochesTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Coches Model
 *
 * @method \App\Model\Entity\Coche get($primaryKey, $options = [])
 * @method \App\Model\Entity\Coche newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Coche[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Coche|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Coche|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Coche patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Coche[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Coche findOrCreate($search, callable $callback = null, $options = [])
 */
class CochesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('coches');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Carrocerias', [
            'foreignKey' => 'id_carroceria',
            'joinType' => 'LEFT',
            'className' => 'Carrocerias'
        ]);

        $this->belongsTo('Combustibles', [
            'foreignKey' => 'id_combustible',
            'joinType' => 'LEFT',
            'className' => 'Combustibles'
        ]);

        $this->belongsTo('MarcasModelos', [
            'foreignKey' => 'id_marca_modelo',
            'joinType' => 'LEFT',
            'className' => 'MarcasModelos'
        ]);

        $this->belongsToMany('Marcas', [
            'foreignKey' => 'id_marca',
            'targetForeignKey' => 'id_marca_modelo',
            'joinTable' => 'marcas_modelos',
            'ClassName' => 'Marcas',
        ]);

        $this->belongsToMany('Modelos', [
            'foreignKey' => 'id_modelo',
            'targetForeignKey' => 'id_marca_modelo',
            'joinTable' => 'marcas_modelos',
            'ClassName' => 'Modelos',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('bastidor')
            ->maxLength('bastidor', 255)
            ->requirePresence('bastidor', 'create')
            ->notEmpty('bastidor');

        $validator
            ->scalar('matricula')
            ->maxLength('matricula', 255)
            ->requirePresence('matricula', 'create')
            ->notEmpty('matricula');

        $validator
            ->integer('n_puertas')
            ->allowEmpty('n_puertas');

        $validator
            ->scalar('color')
            ->maxLength('color', 255)
            ->allowEmpty('color');

        $validator
            ->integer('anyo')
            ->allowEmpty('anyo');

        $validator
            ->integer('id_combustible')
            ->requirePresence('id_combustible', 'create')
            ->notEmpty('id_combustible');

        $validator
            ->integer('id_carroceria')
            ->requirePresence('id_carroceria', 'create')
            ->notEmpty('id_carroceria');

        $validator
            ->requirePresence('id_marca_modelo', 'create')
            ->notEmpty('id_marca_modelo');

        $validator
            ->integer('precio_alquiler')
            ->allowEmpty('precio_alquiler');

        return $validator;
    }
}

cakephp/src/Controller/CochesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use App\Model\Entity\Coche;
use App\Model\Table\CochesTable;
use App\Model\Table\CombustiblesTable;
use Cake\ORM\TableRegistry;

/**
 * Coches Controller
 *
 * @property \App\Model\Table\CochesTable $Coches
 * @property \App\Model\Table\CombustiblesTable $Combustibles
 * @property \App\Model\Table\CarroceriasTable $Carrocerias
 * @property \App\Model\Table\MarcasModelosTable $MarcasModelos
 * @property \App\Model\Table\MarcasTable $Marcas
 * @property \App\Model\Table\ModelosTable $Modelos
 *
 * @method \App\Model\Entity\Coche[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class CochesController extends AppController
{
    public $Combustibles;
    public $Carrocerias;
    public $MarcasModelos;
    public $Marcas;
    public $Modelos;

    public function initialize()
    {
        parent::initialize();
        $this->Combustibles = TableRegistry::get('combustibles');
        $this->Carrocerias = TableRegistry::get('carrocerias');
        $this->MarcasModelos = TableRegistry::get('marcas_modelos');
        $this->Marcas = TableRegistry::get('marcas');
        $this->Modelos = TableRegistry::get('modelos');
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $prueba = $this->Coches->find('all')
            ->select([
                'id', 'bastidor', 'matricula', 'n_puertas',
                'color', 'anyo', 'precio_alquiler'
            ])
            ->select($this->Coches->Carrocerias)
            ->select($this->Coches->Combustibles)
            ->select($this->Coches->MarcasModelos)
            ->select($this->Coches->MarcasModelos->Marcas)
            ->select($this->Coches->MarcasModelos->Modelos)
            ->contain([
                'Carrocerias',
                'Combustibles',
                'MarcasModelos',
                'MarcasModelos.Marcas',
                'MarcasModelos.Modelos',
            ]);
        $coches = $this->paginate($prueba);

        $this->set(compact('coches'));
    }

    /**
     * View method
     *
     * @param string|null $id Coche id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $coche = $this->Coches->get($id, [
            'contain' => [
                'Carrocerias',
                'Combustibles',
                'MarcasModelos',
                'MarcasModelos.Marcas',
                'MarcasModelos.Modelos',
            ]
        ]);

        $this->set('coche', $coche);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $coche = $this->Coches->newEntity();
        $combustibles = $this->getCombustibles();
        $carrocerias = $this->getCarrocerias();
        $marcasModelos = $this->getMarcasModelos();

        if ($this->request->is('post')) {
            $data = $this->request->getData();
            $cocheConBastidor = $this->Coches->find('all')->where(['bastidor' => $data['bastidor']])->first();

            if(isset($cocheConBastidor)){
                $this->Flash->flash(
                    'Ya existe un vehículo con este bastidor. Por favor, añada un vehículo nuevo.',
                    ['params' => ['type' => 'danger']]
                );
                return $this->redirect(['action' => 'add']);
            }

            $cocheConMatricula = $this->Coches->find('all')->where(['matricula' => $data['matricula']])->first();
            if(isset($cocheConMatricula)){
                $this->Flash->flash(
                    'Ya existe un vehículo con esta matrícula. Por favor, añada una matricula nueva.',
                    ['params' => ['type' => 'danger']]
                );
                return $this->redirect(['action' => 'add']);
            }

            $coch = $this->Coches->patchEntity($coche, $this->request->getData());
            if ($this->Coches->save($coche)) {
                $this->Flash->flash('El vehículo se ha añadido correctamente.', ['params' => ['type' => 'success']]);

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->flash(
                'No se ha podido añadir el vehículo. Por favor, inténtelo de nuevo.',
                ['params' => ['type' => 'danger']]
            );
        }
        $this->set(compact('coche', 'combustibles', 'carrocerias', 'marcasModelos'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Coche id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $coche = $this->Coches->get($id, [
            'contain' => [
                'Carrocerias',
                'Combustibles',
                'MarcasModelos',
                'MarcasModelos.Marcas',
                'MarcasModelos.Modelos',
            ]
        ]);

        $combustibles = $this->getCombustibles();
        $carrocerias = $this->getCarrocerias();
        $marcasModelos = $this->getMarcasModelos();

        if ($this->request->is(['patch', 'post', 'put'])) {
            $coche = $this->Coches->patchEntity($coche, $this->request->getData());
            if ($this->Coches->save($coche)) {
                $this->Flash->flash('Los cambios se han guardado correctamente.', ['params' => ['type' => 'success']]);

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->flash(
                'Los cambios no se han podido guardar. Por favor, inténtelo de nuevo.',
                ['params' => ['type' => 'danger']]
            );
        }
        $this->set(compact('coche', 'combustibles', 'carrocerias', 'marcasModelos'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Coch id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $coche = $this->Coches->get($id);
        if ($this->Coches->delete($coche)) {
            $this->Flash->flash('El vehículo se ha sido eliminado.', ['params' => ['type' => 'success']]);
        } else {
            $this->Flash->flash(
                'No se ha podido eliminar el vehículo. Por favor, inténtelo más tarde.',
                ['params' => ['type' => 'danger']]
            );
        }

        return $this->redirect(['action' => 'index']);
    }

    private function getCombustibles()
    {
        $combustiblesData = $this->Combustibles->find('all')->toArray();
        $combustibles = [];
        foreach ($combustiblesData as $combustible){
            $combustibles[$combustible->id] = $combustible->combustible;
        }
        return $combustibles;
    }

    private function getCarrocerias()
    {
        $carroceriasData = $this->Carrocerias->find('all')->toArray();
        $carrocerias = [];
        foreach ($carroceriasData as $carroceria){
            $carrocerias[$carroceria->id] = $carroceria->carroceria;
        }
        return $carrocerias;
    }

    private function getMarcasModelos()
    {
        $marcasModelosData = $this->MarcasModelos->find('all')->toArray();
        $marcasData = $this->Marcas->find('all')->toArray();
        $modelosData = $this->Modelos->find('all')->toArray();

        $marcas = [];
        foreach ($marcasData as $marca){
            $marcas[$marca->id] = $marca->marca;
        }

        $modelos = [];
        foreach ($modelosData as $modelo) {
            $modelos[$modelo->id] = $modelo->modelo;
        }

        $marcasModelos = [];
        foreach ($marcasModelosData as $row){
            $marcasModelos[$row['id']] = $marcas[$row['id_marca']] .' - '. $modelos[$row['id_modelo']];
        }

        return $marcasModelos;
    }
}

cakephp/src/Template/Coches/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface $coche
 */
?>
<div class="row">
    <?= $this->Form->create($coche) ?>
    <fieldset>
        <legend>Añadir Vehículo</legend>

        <p>Si en los desplegables no se muestran los datos requeridos, por favor, añadalos desde los siguientes
            botones:</p>
        <?= $this->Html->link('Añadir Combustibles', ['controller' => 'combustibles', 'action' => 'add'], ['class' => 'btn btn-info btn-sm']) ?>
        <?= $this->Html->link('Añadir Carrocerías', ['controller' => 'carrocerias', 'action' => 'add'], ['class' => 'btn btn-info btn-sm']) ?>
        <?= $this->Html->link('Añadir Marca - Modelo', ['controller' => 'marcasModelos', 'action' => 'add'], ['class' => 'btn btn-info btn-sm']) ?>
        <br/>
        <br/>

        <div class="row">
            <div class="col-md-4">
                <?= $this->Form->control('bastidor'); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('matricula'); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('anyo'); ?>
            </div>
            <div class="col-md-4">

                <?= $this->Form->label('Combustible'); ?>
                <?= $this->Form->select('id_combustible', $combustibles, ['default' => $coche->id_combustible]); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('color'); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('n_puertas',['label' => 'Num Puertas']); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->label('Carroceria'); ?>
                <?= $this->Form->select('id_carroceria', $carrocerias, ['default' => $coche->id_carroceria]); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->label('Marca - Modelo'); ?>
                <?= $this->Form->select('id_marca_modelo', $marcasModelos, ['default' => $coche->id_marca_modelo]); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('precio_alquiler'); ?>
            </div>
        </div>
    </fieldset>

    <?= $this->Form->button('Guardar') ?>
    <?= $this->Form->end() ?>
</div>

cakephp/src/Template/Coches/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface $coch
 */
?>
<div class="row">
    <?= $this->Form->create($coche) ?>
    <fieldset>
        <legend>Editar Vehículo</legend>
        <div class="row">
            <div class="col-md-4">
                <?= $this->Form->control('bastidor'); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('matricula'); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('anyo'); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->label('Combustible'); ?>
                <?= $this->Form->select('id_combustible', $combustibles, ['default' => $coche->id_combustible]); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('color'); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('n_puertas'); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->label('Carroceria'); ?>
                <?= $this->Form->select('id_carroceria', $carrocerias, ['default' => $coche->id_carroceria]); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->label('Marca - Modelo'); ?>
                <?= $this->Form->select('id_marca_modelo', $marcasModelos, ['default' => $coche->id_marca_modelo]); ?>
            </div>
            <div class="col-md-4">
                <?= $this->Form->control('precio_alquiler'); ?>
            </div>
        </div>
    </fieldset>
    <?= $this->Form->button('Guardar') ?>
    <?= $this->Form->end() ?>
</div>

cakephp/src/Template/Coches/index.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface[]|\Cake\Collection\CollectionInterface $coches
 */
?>
<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h2>Vehículos</h2>
        </div>
        <br/>
        <?= $this->Html->link('Añadir Vehículo', ['action' => 'add'], ['class' => 'btn btn-info']) ?>

        <br/><br/>

        <h5>Lista de Vehículos:</h5>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th scope="col"><?= $this->Paginator->sort('Id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Bastidor') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Matricula') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Año') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Combustible') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Color') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Num Puertas') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Carroceria') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Marca') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Modelo') ?></th>
                <th scope="col"><?= $this->Paginator->sort('Precio Alquiler') ?></th>
                <th scope="col" class="actions">Acciones</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($coches as $coche): ?>
            <tr>
                <td><?= $this->Number->format($coche->id) ?></td>
                <td><?= h($coche->bastidor) ?></td>
                <td><?= h($coche->matricula) ?></td>
                <td><?= h($coche->anyo) ?></td>
                <td><?= h($coche->combustible->combustible) ?></td>
                <td><?= h($coche->color) ?></td>
                <td><?= $this->Number->format($coche->n_puertas) ?></td>
                <td><?= h($coche->carroceria->carroceria) ?></td>
                <td><?= h($coche->marcas_modelo->marca->marca) ?></td>
                <td><?= h($coche->marcas_modelo->modelo->modelo) ?></td>
                <td><?= $this->Number->format($coche->precio_alquiler) ?></td>
                <td class="actions">
                    <?= $this->Html->link('Ver', ['action' => 'view', $coche->id]) ?>
                    <?= $this->Html->link('Editar', ['action' => 'edit', $coche->id]) ?>
                    <?= $this->Form->postLink('Eliminar', ['action' => 'delete', $coche->id], ['confirm' => '¿Estás seguro de que quieres eliminar el vehículo?']) ?>
                </td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div class="paginator">
            <ul class="pagination">
                <?= $this->Paginator->first('<< ' . 'primera') ?>
                <?= $this->Paginator->prev('< ' . 'anterior') ?>
                <?= $this->Paginator->numbers(['before' => '', 'after' => '']) ?>
                <?= $this->Paginator->next(' siguiente ' . ' >') ?>
                <?= $this->Paginator->last(' última ' . ' >>') ?>
            </ul>
            <p><?= $this->Paginator->counter(['format' => 'Página {{page}} de {{pages}}, mostrando {{current}}
                registro(s) de un total de {{count}}.']) ?></p>
        </div>
    </div>
</div>

cakephp/src/Template/Coches/view.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface $coche
 */
?>

<div class="row">
    <div class="col-md-12">
        <h5>Datos del vehículo:</h5>
        <p><strong>Id:</strong> <?= h($coche->id) ?></p>
        <p><strong>Bastidor:</strong> <?= $this->Number->format($coche->precio_alquiler) ?></p>
        <p><strong>Matrícula:</strong> <?= h($coche->matricula) ?></p>
        <p><strong>Año:</strong> <?= h($coche->anyo) ?></p>
        <p><strong>Combustible:</strong> <?= h($coche->combustible->combustible) ?></p>
        <p><strong>Color:</strong> <?= h($coche->color) ?></p>
        <p><strong>Num Puertas:</strong> <?= $this->Number->format($coche->n_puertas) ?></p>
        <p><strong>Carrocería:</strong> <?= h($coche->carroceria->carroceria) ?></p>
        <p><strong>Marca:</strong> <?= h($coche->marcas_modelo->marca->marca) ?></p>
        <p><strong>Modelo:</strong> <?= h($coche->marcas_modelo->modelo->modelo) ?></p>
        <p><strong>Precio Alquiler:</strong> <?= $this->Number->format($coche->precio_alquiler) ?></p>

        <br/>
        <?= $this->Html->link('Editar Vehículo', ['action' => 'edit', $coche->id], ['class' => 'btn btn-info']) ?>
        <?= $this->Form->postLink('Eliminar Vehículo', ['action' => 'delete', $coche->id], ['class' => 'btn btn-info', 'confirm' => '¿Estás seguro de que quieres eliminar este vehículo?']) ?>
        <?= $this->Html->link('Lista de Vehículos', ['action' => 'index'], ['class' => 'btn btn-info']) ?>
    </div>
</div>